import * as THREE from '../bosque/libs/three.module.js';
import { GLTFLoader } from '../bosque/bike-runtime/loaders/GLTFLoader.js';

const scene=new THREE.Scene();scene.background=new THREE.Color(0x101820);
const camera=new THREE.PerspectiveCamera(54,innerWidth/innerHeight,.03,120);
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.2));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.shadowMap.enabled=false;document.body.prepend(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xdcecff,0x2c1c18,2.2));const key=new THREE.DirectionalLight(0xffd5e8,2.6);key.position.set(4,8,5);scene.add(key);
const loading=document.getElementById('loading'),status=document.getElementById('status');
let avatarRoot=null,hairGroup=null,mixer=null,orbitYaw=0,orbitPitch=.08,orbitDistance=2.35,drag=false,lastX=0,lastY=0;

function normalize(object,targetHeight=1.78){object.position.set(0,0,0);object.rotation.set(0,0,0);object.scale.set(1,1,1);object.updateMatrixWorld(true);let box=new THREE.Box3().setFromObject(object);let size=box.getSize(new THREE.Vector3());const scale=targetHeight/Math.max(.001,size.y);object.scale.setScalar(scale);object.updateMatrixWorld(true);box=new THREE.Box3().setFromObject(object);const center=box.getCenter(new THREE.Vector3());object.position.set(-center.x,-box.min.y,-center.z);}
function findClip(clips,names){for(const n of names){const exact=clips.find(c=>String(c.name).toLowerCase()===n);if(exact)return exact;}for(const n of names){const partial=clips.find(c=>String(c.name).toLowerCase().includes(n));if(partial)return partial;}return clips[0]||null;}
function makeHair(style){hairGroup?.parent?.remove(hairGroup);hairGroup=new THREE.Group();hairGroup.position.set(0,1.68,0);const mat=new THREE.MeshStandardMaterial({color:0x17100c,roughness:.92});
  if(style==='afro'){const m=new THREE.Mesh(new THREE.SphereGeometry(.27,18,12),mat);m.scale.y=.9;hairGroup.add(m);}else if(style==='cresta'){const m=new THREE.Mesh(new THREE.BoxGeometry(.09,.30,.42),mat);m.position.y=.08;hairGroup.add(m);}else if(style==='clasico'){for(let i=-2;i<=2;i++){const m=new THREE.Mesh(new THREE.SphereGeometry(.105,12,8),mat);m.position.set(i*.075,0,Math.abs(i)*.018);hairGroup.add(m);}}else if(style==='corto'){const m=new THREE.Mesh(new THREE.SphereGeometry(.19,16,10,0,Math.PI*2,0,Math.PI*.58),mat);m.position.y=-.01;hairGroup.add(m);}else hairGroup.visible=false;
  avatarRoot?.add(hairGroup);localStorage.setItem('vice_city_hair_style',style);document.querySelectorAll('[data-style]').forEach(b=>b.classList.toggle('active',b.dataset.style===style));status.textContent=`Corte ${style.toUpperCase()} aplicado. Se conservará al regresar a GTA MANUCHO.`;
}
function fallbackRoom(){const floor=new THREE.Mesh(new THREE.BoxGeometry(10,.2,8),new THREE.MeshStandardMaterial({color:0x222b31,roughness:1}));scene.add(floor);for(const z of [-3.9,3.9]){const w=new THREE.Mesh(new THREE.BoxGeometry(10,4,.15),new THREE.MeshStandardMaterial({color:0x5b4550}));w.position.set(0,2,z);scene.add(w);}for(const x of [-4.9,4.9]){const w=new THREE.Mesh(new THREE.BoxGeometry(.15,4,8),new THREE.MeshStandardMaterial({color:0x35414a}));w.position.set(x,2,0);scene.add(w);}const chair=new THREE.Mesh(new THREE.CylinderGeometry(.5,.62,.72,16),new THREE.MeshStandardMaterial({color:0x1e242a,metalness:.2}));chair.position.set(0,.36,.55);scene.add(chair);}
async function boot(){try{const room=await new GLTFLoader().loadAsync('../venue-assets/barber/RoomModel.glb');const model=room.scene;model.traverse(o=>{if(o.isMesh){o.castShadow=false;o.receiveShadow=false;const mats=Array.isArray(o.material)?o.material:[o.material];for(const m of mats)if(m)m.side=THREE.DoubleSide;}});model.updateMatrixWorld(true);let box=new THREE.Box3().setFromObject(model),size=box.getSize(new THREE.Vector3());const scale=11/Math.max(size.x,size.z,.001);model.scale.setScalar(scale);model.updateMatrixWorld(true);box=new THREE.Box3().setFromObject(model);const center=box.getCenter(new THREE.Vector3());model.position.set(-center.x,-box.min.y,-center.z);scene.add(model);}catch(e){console.warn(e);fallbackRoom();}
  const gltf=await new GLTFLoader().loadAsync('../models/gltf/Soldier.glb');avatarRoot=new THREE.Group();normalize(gltf.scene);avatarRoot.add(gltf.scene);avatarRoot.position.set(0,0,.35);scene.add(avatarRoot);mixer=new THREE.AnimationMixer(gltf.scene);mixer.clipAction(findClip(gltf.animations,['idle']))?.play();makeHair(localStorage.getItem('vice_city_hair_style')||'corto');loading.style.display='none';}
function updateCamera(){const target=new THREE.Vector3(0,1.05,.15);camera.position.set(target.x+Math.sin(orbitYaw)*Math.cos(orbitPitch)*orbitDistance,target.y+Math.sin(orbitPitch)*orbitDistance,target.z+Math.cos(orbitYaw)*Math.cos(orbitPitch)*orbitDistance);camera.lookAt(target);}
renderer.domElement.addEventListener('pointerdown',e=>{drag=true;lastX=e.clientX;lastY=e.clientY;renderer.domElement.setPointerCapture?.(e.pointerId);});renderer.domElement.addEventListener('pointermove',e=>{if(!drag)return;orbitYaw-=(e.clientX-lastX)*.007;orbitPitch=THREE.MathUtils.clamp(orbitPitch+(e.clientY-lastY)*.004,-.22,.5);lastX=e.clientX;lastY=e.clientY;});renderer.domElement.addEventListener('pointerup',()=>drag=false);renderer.domElement.addEventListener('wheel',e=>{orbitDistance=THREE.MathUtils.clamp(orbitDistance+Math.sign(e.deltaY)*.28,1.8,4.4);},{passive:true});
document.querySelectorAll('[data-style]').forEach(button=>button.addEventListener('click',()=>makeHair(button.dataset.style)));document.getElementById('return').addEventListener('click',()=>location.href='../index.html?from=barberia');
window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.2));});
let last=performance.now();renderer.setAnimationLoop(()=>{const now=performance.now(),dt=Math.min(.05,(now-last)/1000);last=now;mixer?.update(dt);updateCamera();renderer.render(scene,camera);});boot().catch(e=>{console.error(e);loading.textContent='NO SE PUDO ABRIR LA BARBERÍA';});
