import * as THREE from '../bosque/libs/three.module.js';
import { GLTFLoader } from '../bosque/bike-runtime/loaders/GLTFLoader.js';
import { DRACOLoader } from '../bosque/bike-runtime/loaders/DRACOLoader.js';

const scene=new THREE.Scene();scene.background=new THREE.Color(0x11161b);scene.fog=new THREE.Fog(0x11161b,18,52);
const camera=new THREE.PerspectiveCamera(65,innerWidth/innerHeight,.04,100);const renderer=new THREE.WebGLRenderer({antialias:false,powerPreference:'high-performance',stencil:false});renderer.setPixelRatio(Math.min(devicePixelRatio,1));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.shadowMap.enabled=false;document.body.prepend(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xe7f1ff,0x2d2019,2));const sun=new THREE.DirectionalLight(0xffe1c7,2.3);sun.position.set(7,13,5);scene.add(sun);
const player={position:new THREE.Vector3(0,0,4),yaw:Math.PI,pitch:-.08,speed:0};const keys=Object.create(null);let avatar=null,mixer=null,actions={},action='idle',cameraMode='third',training=false,trainUntil=0,lastTrain=0;let points=Number(localStorage.getItem('vice_city_gym_points')||0);const pointNode=document.getElementById('points'),prompt=document.getElementById('prompt'),loading=document.getElementById('loading');pointNode.textContent=points;
const trainingSpot=new THREE.Vector3(0,0,-2.3);const bag=new THREE.Group();const bagMesh=new THREE.Mesh(new THREE.CylinderGeometry(.38,.42,1.55,16),new THREE.MeshStandardMaterial({color:0xa51f1f,roughness:.65}));bagMesh.position.y=1.45;const chain=new THREE.Mesh(new THREE.CylinderGeometry(.035,.035,1.0,8),new THREE.MeshStandardMaterial({color:0x777777,metalness:.7}));chain.position.y=2.72;bag.add(bagMesh,chain);bag.position.copy(trainingSpot);scene.add(bag);const ring=new THREE.Mesh(new THREE.RingGeometry(.75,.9,32),new THREE.MeshBasicMaterial({color:0xff5b39,side:THREE.DoubleSide,transparent:true,opacity:.75}));ring.rotation.x=-Math.PI/2;ring.position.copy(trainingSpot);ring.position.y=.012;scene.add(ring);
function clip(names,clips){for(const n of names){const e=clips.find(c=>String(c.name).toLowerCase()===n);if(e)return e;}for(const n of names){const e=clips.find(c=>String(c.name).toLowerCase().includes(n));if(e)return e;}return clips[0];}
function setAction(name){if(action===name)return;actions[action]?.fadeOut(.12);actions[name]?.reset().fadeIn(.12).play();action=name;}
function normalize(object,target=1.78){object.position.set(0,0,0);object.rotation.set(0,0,0);object.scale.set(1,1,1);object.updateMatrixWorld(true);let box=new THREE.Box3().setFromObject(object),size=box.getSize(new THREE.Vector3());object.scale.setScalar(target/Math.max(.001,size.y));object.updateMatrixWorld(true);box=new THREE.Box3().setFromObject(object);const center=box.getCenter(new THREE.Vector3());object.position.set(-center.x,-box.min.y,-center.z);}
function fallbackGym(){const floor=new THREE.Mesh(new THREE.BoxGeometry(24,.2,20),new THREE.MeshStandardMaterial({color:0x303235,roughness:1}));floor.position.y=-.1;scene.add(floor);for(let i=-2;i<=2;i++){const bench=new THREE.Mesh(new THREE.BoxGeometry(2,.35,.7),new THREE.MeshStandardMaterial({color:0x22262b}));bench.position.set(i*3.5,.3,3);scene.add(bench);}const wall=new THREE.Mesh(new THREE.BoxGeometry(24,5,.2),new THREE.MeshStandardMaterial({color:0x4b2e28}));wall.position.set(0,2.5,-10);scene.add(wall);}
async function loadGym(){try{const draco=new DRACOLoader();draco.setDecoderPath('../venue-assets/gym/draco/');const loader=new GLTFLoader();loader.setDRACOLoader(draco);const gltf=await loader.loadAsync('../venue-assets/gym/BoxingGym-draco.gltf');const model=gltf.scene;model.traverse(o=>{if(o.isMesh){o.castShadow=false;o.receiveShadow=false;o.frustumCulled=true;}});model.updateMatrixWorld(true);let box=new THREE.Box3().setFromObject(model),size=box.getSize(new THREE.Vector3());const scale=24/Math.max(size.x,size.z,.001);model.scale.setScalar(scale);model.updateMatrixWorld(true);box=new THREE.Box3().setFromObject(model);const center=box.getCenter(new THREE.Vector3());model.position.set(-center.x,-box.min.y,-center.z);scene.add(model);draco.dispose?.();}catch(e){console.warn(e);fallbackGym();}}
async function loadPlayer(){const gltf=await new GLTFLoader().loadAsync('../models/gltf/Soldier.glb');normalize(gltf.scene);avatar=new THREE.Group();avatar.add(gltf.scene);scene.add(avatar);mixer=new THREE.AnimationMixer(gltf.scene);actions={idle:mixer.clipAction(clip(['idle'],gltf.animations)),walk:mixer.clipAction(clip(['walk'],gltf.animations)),run:mixer.clipAction(clip(['run'],gltf.animations))};actions.idle?.play();}
function startTraining(now){if(now-lastTrain<700||player.position.distanceToSquared(trainingSpot)>2.6*2.6)return;lastTrain=now;training=true;trainUntil=now+520;points+=5;localStorage.setItem('vice_city_gym_points',String(points));pointNode.textContent=points;bag.rotation.z=(Math.random()>.5?1:-1)*.22;setTimeout(()=>bag.rotation.z=0,240);setAction('run');}
function update(dt,now){if(training&&now>=trainUntil)training=false;const f=(keys.KeyW?1:0)-(keys.KeyS?1:0),side=(keys.KeyD?1:0)-(keys.KeyA?1:0),moving=Boolean(f||side);if(moving&&!training){const forward=new THREE.Vector3(-Math.sin(player.yaw),0,-Math.cos(player.yaw)),right=new THREE.Vector3(Math.cos(player.yaw),0,-Math.sin(player.yaw));const dir=forward.multiplyScalar(f).addScaledVector(right,side).normalize();const speed=(keys.ShiftLeft?5.2:3.1);player.position.addScaledVector(dir,speed*dt);player.position.x=THREE.MathUtils.clamp(player.position.x,-10.5,10.5);player.position.z=THREE.MathUtils.clamp(player.position.z,-8.5,8.5);const target=Math.atan2(dir.x,dir.z)+Math.PI;const delta=Math.atan2(Math.sin(target-avatar.rotation.y),Math.cos(target-avatar.rotation.y));avatar.rotation.y+=delta*Math.min(1,dt*12);}avatar.position.copy(player.position);avatar.visible=cameraMode==='third';setAction(training?'run':moving?(keys.ShiftLeft?'run':'walk'):'idle');mixer?.update(dt*(keys.ShiftLeft?1.15:1));const near=player.position.distanceToSquared(trainingSpot)<2.6*2.6;prompt.style.display=near?'block':'none';ring.material.opacity=.55+Math.sin(now*.005)*.22;
  const eye=player.position.clone().add(new THREE.Vector3(0,1.6,0)),view=new THREE.Vector3(-Math.sin(player.yaw)*Math.cos(player.pitch),Math.sin(player.pitch),-Math.cos(player.yaw)*Math.cos(player.pitch));if(cameraMode==='first'){camera.position.copy(eye);camera.lookAt(eye.clone().addScaledVector(view,8));}else{const horizontal=new THREE.Vector3(view.x,0,view.z).normalize();camera.position.lerp(eye.clone().addScaledVector(horizontal,-4.2).add(new THREE.Vector3(0,1.1,0)),1-Math.pow(.003,dt));camera.lookAt(eye.clone().addScaledVector(view,7));}}
renderer.domElement.addEventListener('click',()=>renderer.domElement.requestPointerLock?.());document.addEventListener('mousemove',e=>{if(document.pointerLockElement!==renderer.domElement)return;player.yaw-=e.movementX*.0022;player.pitch=THREE.MathUtils.clamp(player.pitch-e.movementY*.0018,-.75,.45);});document.addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='KeyE')startTraining(performance.now());if(e.code==='KeyV')cameraMode=cameraMode==='third'?'first':'third';});document.addEventListener('keyup',e=>keys[e.code]=false);document.getElementById('exit').addEventListener('click',()=>location.href='../index.html?from=gimnasio');window.addEventListener('blur',()=>Object.keys(keys).forEach(k=>keys[k]=false));window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1));});
let last=performance.now();async function boot(){await Promise.all([loadGym(),loadPlayer()]);loading.style.display='none';renderer.domElement.requestPointerLock?.();renderer.setAnimationLoop(()=>{const now=performance.now(),dt=Math.min(.05,(now-last)/1000);last=now;update(dt,now);renderer.render(scene,camera);});}boot().catch(e=>{console.error(e);loading.textContent='NO SE PUDO CARGAR EL GIMNASIO';fallbackGym();});
